### ISSUE TITLE
Add a notice if user asks for coverage without whitelist

### ISSUE THREAD

**Issue by liorchamla** [pestphp/pest#13]
Hey all, as Nuno asked me to, I post this new issue referencing https://github.com/pestphp/pest/issues/12 : when you ask for `--coverage` you must have a whitelist in order to tell PHPUnit which files you want to monitor for coverage.

For now, you will just have a ShouldNotHappenException which states that coverage could not be done. 

It could be usefull for beginners (like me) to suggest that maybe a whitelist is missing or even to prevent the use of `--coverage` option if no whitelist is set in the command nor in the phpunit.xml ?

I will try to see if I can do this by myself and give you all a PR but I'm not sure I'm competent enough and wont have time to do it soon, so if someone wants to give it a try, let's go 👍

**Comment by liorchamla** [comment]
Weird thing btw, when I tried to work on a solution to implement this, I found these lines inside  `PHPUnit\TextUI\TestRunner` (around line 578) : 
```php
if (!$this->codeCoverageFilter->hasWhitelist()) {
    if (!$whitelistFromConfigurationFile && !$whitelistFromOption) {
        $this->writeMessage('Error', 'No whitelist is configured, no code coverage will be generated.');
    } else {
        $this->writeMessage('Error', 'Incorrect whitelist config, no code coverage will be generated.');
    }

    $codeCoverageReports = 0;

    unset($codeCoverage);
}
```

So it seems this situation is already addressed by PHPUnit itself. Will look around to see what can be done.

**Comment by nunomaduro** [comment]
I think we are not show those messages... It may have something todo with the printer. Thanks for reporting this...

**Comment by nunomaduro** [comment]
I'm closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version.

**Comment by owenvoke** [comment]
I will add a section to the docs on this, it's still an issue. But by default we add `src` and `app`, which covers most libraries so it probably doesn't come up much.
