### ISSUE TITLE
[Bug]: TestResult::fromBeforeFirstTestMethodErrored Argument TypeError

### ISSUE THREAD

**Issue by calebdw** [pestphp/pest#1386]
### What Happened

Hello!

We started receiving this error after upgrading => v3.7.2, we've had to pin the pest version at v3.7.1 for our CI to pass (it is still an issue as of v3.8.1).

```
   TypeError 
  NunoMaduro\Collision\Adapters\Phpunit\TestResult::fromBeforeFirstTestMethodErrored(): Argument #1 ($event) must be of type PHPUnit\Event\Test\BeforeFirstTestMethodErrored, PHPUnit\Event\Test\AfterLastTestMethodErrored given, called in /builds/.../vendor/pestphp/pest/src/Support/StateGenerator.php on line 34
  at vendor/nunomaduro/collision/src/Adapters/Phpunit/TestResult.php:178
    174▕ 
    175▕     /**
    176▕      * Creates a new test from the given test case.
    177▕      */
  ➜ 178▕     public static function fromBeforeFirstTestMethodErrored(BeforeFirstTestMethodErrored $event): self
    179▕     {
    180▕         if (is_subclass_of($event->testClassName(), HasPrintableTestCaseName::class)) {
    181▕             $testCaseName = $event->testClassName()::getPrintableTestCaseName();
    182▕         } else {
```

### How to Reproduce

See above

### Pest Version

2.8.1

### PHP Version

8.4.x

### Operation System

Linux

**Comment by calebdw** [comment]
Looks like this might have been fixed in 3.8.3

**Comment by ZachWatkins** [comment]
This still occurs for me in pestphp/pest@^4.0.

**Edit: @calebdw This was my mistake - I was using Laravel's `Storage` facade in the `afterAll` hook which must have failed silently until upgrading Laravel to v12 and/or Pest to v4.**

**Comment by ZachWatkins** [comment]
> This still occurs for me in pestphp/pest@^4.0.

This was my mistake - I was using Laravel's `Storage` facade in the `afterAll` hook which must have failed silently until upgrading Laravel to v12 and/or Pest to v4.

Replying in case automations triggered by issue replies are more helpful than just editing my comment.
