### ISSUE TITLE
[Bug]: OOM errors on v4

### ISSUE THREAD

**Issue by calebdw** [pestphp/pest#1449]
### What Happened

Hello!

I've upgraded to Pest v4 and PHPUnit 12 (no other changes). Pest seems to pass, but then it dies at the very end with an OOM error. This same test suite passes just fine on v3

```
$ if [[ $TEST_COVERAGE == "true" ]]; then # collapsed multi-line command
  sss.....!!.....................................................................................................................s........................................
  ..........................................................................................................................s...ss..ss.............s..............s.......
  .......s..............s..............s...........................................s................s.....................................................................
  .........................................s....................s.........................................................s...............................................
  ............s............................................................................................................s...............................s.............s
  ...............................s.............s....................................s...............................................s....................s................
  ..............................................!...............................................................!....................s....................................
  ......................................................................s!..............s................s.sss.....sss..............s........................s...ssssssss.
  ...................s................s..............s..............s.....................................................................................................
  .....s.............................s..................s......................s.........................................s..........................s.....................
  .....................s.................................s..............s.........................s..........................................s...........................s
  ..............s..............s.....................................................................................s....................................................
  .....s.........................................!......!..................s....s.......................s.................................................!...............
  ..................s......!!....................s.......................................s...................s...........................................s................
  ...........................s.......................................................................................................................s....................
  .............................................................................................s.................s........................................................
  .................................................................................................................s.................................!....................
  ...........................................................................................!!................................................!!!!.......................
  ........................................................................................................................................................................
  ..................................................................................................................!.....................................................
  ..............................................!.........................................................................................................................
  ........!..................................................................................................................................................!............
  ........................................................................................................................................................................
  ............!.................................................!.............!...........................................................................................
  ...........................!............................................................................................................................................
  ...............................ssss.....................................................................................................................................
  .................................................................................................................................................s......................
  ........................................................................................................................................................................
  ........................................................................................................................................................................
  ...............................................................................................................
  Tests:    25 incomplete, 86 skipped, 4872 passed (22578 assertions)
  Duration: 247.43s
  Parallel: 16 processes
Fatal error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 94801320 bytes) in /tmp/worker_14_stdout_68a72ebe127f2_coverage on line 2
   Pest\Exceptions\FatalException 
  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 94801320 bytes)
  at /tmp/worker_14_stdout_68a72ebe127f2_coverage:2
Fatal error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 94809608 bytes) in vendor/filp/whoops/src/Whoops/Exception/Frame.php on line 120
```

Thanks!

### How to Reproduce

Here's the command used to run pest in ci:

```bash
XDEBUG_MODE=coverage vendor/bin/pest -p --processes=16 --log-junit=junit/pest.xml \
  --coverage-cobertura=coverage/coverage.xml --coverage-text=coverage/coverage.txt
```

### Pest Version

4.0.0

### PHP Version

8.4

### Operation System

Linux

**Comment by nunomaduro** [comment]
Same issue as https://github.com/pestphp/pest/issues/1442, we are going to fix that today/tomorrow.

**Comment by nunomaduro** [comment]
fixed on `v4.0.2`

**Comment by calebdw** [comment]
@nunomaduro, I'm still getting OOM errors after all the tests pass on `v4.0.2`:

```
  ...............................................................................................................
  Tests:    25 incomplete, 86 skipped, 4872 passed (22689 assertions)
  Duration: 294.03s
  Parallel: 16 processes
Fatal error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 94792808 bytes) in /tmp/worker_13_stdout_68a86d3817b84_coverage on line 3
   Pest\Exceptions\FatalException 
  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 94792808 bytes)
  at /tmp/worker_13_stdout_68a86d3817b84_coverage:3
Fatal error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 94801096 bytes) in vendor/filp/whoops/src/Whoops/Exception/Frame.php on line 120
```
